In [2]:
import numpy as np

In [3]:
a= np.array([1,2,3])
print(a)
print(a.shape)
b = np.array([
    [1,2,3],
    [4,5,6]
    ])
print(b)
print(b.shape)

[1 2 3]
(3,)
[[1 2 3]
 [4 5 6]]
(2, 3)


In [4]:
c= np.arange(1, 10, .2) # start, end, step
print(c)
print(c.shape)
d= np.linspace(1, 10, 50)   # start, end, number of elements
print(d)

[1.  1.2 1.4 1.6 1.8 2.  2.2 2.4 2.6 2.8 3.  3.2 3.4 3.6 3.8 4.  4.2 4.4
 4.6 4.8 5.  5.2 5.4 5.6 5.8 6.  6.2 6.4 6.6 6.8 7.  7.2 7.4 7.6 7.8 8.
 8.2 8.4 8.6 8.8 9.  9.2 9.4 9.6 9.8]
(45,)
[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]


In [5]:
# For finding out the dimension of an array
print(c.ndim)   
print(d.ndim)
print(b.ndim)

1
1
2


In [6]:
print(c.reshape(9,5))

[[1.  1.2 1.4 1.6 1.8]
 [2.  2.2 2.4 2.6 2.8]
 [3.  3.2 3.4 3.6 3.8]
 [4.  4.2 4.4 4.6 4.8]
 [5.  5.2 5.4 5.6 5.8]
 [6.  6.2 6.4 6.6 6.8]
 [7.  7.2 7.4 7.6 7.8]
 [8.  8.2 8.4 8.6 8.8]
 [9.  9.2 9.4 9.6 9.8]]


In [7]:
print(c.reshape(3, 3, 5))
print(c.ndim)

[[[1.  1.2 1.4 1.6 1.8]
  [2.  2.2 2.4 2.6 2.8]
  [3.  3.2 3.4 3.6 3.8]]

 [[4.  4.2 4.4 4.6 4.8]
  [5.  5.2 5.4 5.6 5.8]
  [6.  6.2 6.4 6.6 6.8]]

 [[7.  7.2 7.4 7.6 7.8]
  [8.  8.2 8.4 8.6 8.8]
  [9.  9.2 9.4 9.6 9.8]]]
1


In [8]:
np.random.randint(1, 1000, (3,3))   # (3,3) is the tuple

array([[  6, 390, 884],
       [408,  60,  84],
       [524, 604, 773]])

- Maths in numpy

In [9]:
x = np.array([
    [2,3,4],
    [5,6,7]
])
y = np.array([
    [1,2,3],
    [4,7,9]
])

In [10]:
print(x + y)
print(x - y)
print(x * y)
print(x / y)
print(x ** y)
print(x % y)

[[ 3  5  7]
 [ 9 13 16]]
[[ 1  1  1]
 [ 1 -1 -2]]
[[ 2  6 12]
 [20 42 63]]
[[2.         1.5        1.33333333]
 [1.25       0.85714286 0.77777778]]
[[       2        9       64]
 [     625   279936 40353607]]
[[0 1 1]
 [1 6 7]]


In [11]:
print(x * 2)    # scalar multiplication
print(x / 2)    # scalar division
print(x ** 2)   # scalar
print(x % 2)    # scalar modulus

[[ 4  6  8]
 [10 12 14]]
[[1.  1.5 2. ]
 [2.5 3.  3.5]]
[[ 4  9 16]
 [25 36 49]]
[[0 1 0]
 [1 0 1]]


In [12]:
# matrix multiplication (many ways are possible for the same result)
print(x.dot(y.T))   # '.T' is for transposition
print(np.matmul(x,y.T))
print(x @ y.T)

[[ 20  65]
 [ 38 125]]
[[ 20  65]
 [ 38 125]]
[[ 20  65]
 [ 38 125]]


In [13]:
# statistical functions
print(x.sum())  # sum of all elements
print(x.sum(axis=0))    # sum of columns
print(x.sum(axis=1))    # sum of rows
print(x.mean()) # mean of all elements
print(x.std())  # standard deviation of all elements
print(x.min())  # minimum of all elements
print(x.max())  # maximum of all elements
print(x.argmax())   # index of maximum element
print(x.argmin())   # index of minimum element

27
[ 7  9 11]
[ 9 18]
4.5
1.707825127659933
2
7
5
0


In [14]:
# Trigonometric functions
print(np.sin(x))
print(np.cos(x))
print(np.tan(x))
print(np.arcsin(x)) # inverse sin


[[ 0.90929743  0.14112001 -0.7568025 ]
 [-0.95892427 -0.2794155   0.6569866 ]]
[[-0.41614684 -0.9899925  -0.65364362]
 [ 0.28366219  0.96017029  0.75390225]]
[[-2.18503986 -0.14254654  1.15782128]
 [-3.38051501 -0.29100619  0.87144798]]
[[nan nan nan]
 [nan nan nan]]


C:\Users\abhis\AppData\Local\Temp\ipykernel_28560\60929417.py:5: RuntimeWarning: invalid value encountered in arcsin
  print(np.arcsin(x)) # inverse sin


In [15]:
# indexing and slicing
print(x[0, 0])  # first row, first column
print(x[0, :])  # first row, all columns
print(x[:, 0])  # all rows, first column
print(x[:2, :2])    #   first two rows, first two columns
print(x[:2])    #   first two rows, all columns

2
[2 3 4]
[2 5]
[[2 3]
 [5 6]]
[[2 3 4]
 [5 6 7]]
